pub const CHAR_EIGHT: usize = 8;
pub const CHAR_WIDTH: usize = 8;
pub const SPACE_WIDTH: usize = 2;
pub const TOTAL_WIDTH: usize = CHAR_WIDTH + SPACE_WIDTH;
pub const SPACE_HEIGHT: usize = 2;
pub const TOTAL_EIGHT: usize = CHAR_EIGHT + SPACE_HEIGHT;

pub fn font_char(c: char, b: (u8, u8, u8), w: (u8, u8, u8)) -> [[(u8, u8, u8); CHAR_WIDTH]; CHAR_EIGHT] {
    return match c {
        ' ' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
        ],
        'a' => [
            [b, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, b],
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
            [b, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, w, w],
            [b, w, w, w, w, w, b, w],
        ],
        'b' => [
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
        ],
        'c' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, w],
        ],
        'd' => [
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
            [b, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, w, w, w, w, w, w],
        ],
        'e' => [
            [b, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, w],
        ],
        'f' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, w, w, w, w, w],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
        ],
        'g' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, w],
            [b, w, w, w, w, w, w, w],
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
        ],
        'h' => [
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
        ],
        'i' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, w, w, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [w, w, w, w, w, w, w, w],
        ],
        'j' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, w, w, w, b, b],
            [b, b, b, b, b, w, b, b],
            [w, b, b, b, b, w, b, b],
            [w, b, b, b, b, w, b, b],
            [b, w, w, w, w, b, b, b],
        ],
        'k' => [
            [b, b, b, b, b, b, b, b],
            [w, b, b, b, b, w, w, b],
            [w, b, b, b, w, b, b, b],
            [w, b, b, w, b, b, b, b],
            [w, b, w, b, b, b, b, b],
            [w, w, b, b, b, b, b, b],
            [w, b, w, b, b, b, b, b],
            [w, b, b, w, w, b, b, b],
        ],
        'l' => [
            [b, b, b, b, b, b, b, b],
            [w, w, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, b, w, w, w, w, w],
        ],
        'm' => [
            [b, b, b, b, b, b, b, b],
            [b, w, w, b, w, w, w, b],
            [w, b, b, w, b, b, b, w],
            [w, b, b, w, b, b, b, w],
            [w, b, b, w, b, b, b, w],
            [w, b, b, w, b, b, b, w],
            [w, b, b, w, b, b, b, w],
            [w, b, b, w, b, b, b, w],
        ],
        'n' => [
            [b, b, b, b, b, b, b, b],
            [w, b, w, w, w, w, w, b],
            [w, w, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
        ],
        'o' => [
            [b, b, b, b, b, b, b, b],
            [b, b, w, w, w, w, b, b],
            [b, w, b, b, b, b, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, w, b],
            [b, b, w, w, w, w, b, b],
        ],
        'p' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
        ],
        'q' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, w, w, w, w, w, w],
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
        ],
        'r' => [
            [b, b, b, b, b, b, b, b],
            [w, b, w, w, w, w, w, w],
            [w, w, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
        ],
        's' => [
            [b, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, b],
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
        ],
        't' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [w, w, w, w, w, w, w, w],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, b, w, w, w, w],
        ],
        'u' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, w, b],
            [b, b, w, w, w, w, b, b],
        ],
        'v' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, w, b],
            [b, b, w, b, b, w, b, b],
            [b, b, b, w, w, b, b, b],
            [b, b, b, w, b, b, b, b],
        ],
        'w' => [
            [b, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, b, w, w, b, w, b],
            [b, w, b, w, w, b, w, b],
            [b, w, b, w, b, b, w, b],
            [b, b, w, b, b, w, b, b],
            [b, b, w, b, b, w, b, b],
        ],
        'x' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, w, b],
            [b, b, w, b, b, w, b, b],
            [b, b, b, w, w, b, b, b],
            [b, w, w, b, b, w, w, b],
            [w, b, b, b, b, b, b, w],
        ],
        'y' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, w, b, b, b, b, b, w],
            [b, b, w, b, b, b, w, b],
            [b, b, b, w, b, w, b, b],
            [b, b, b, b, w, b, b, b],
            [b, b, b, w, b, b, b, b],
            [w, w, w, b, b, b, b, b],
        ],
        'z' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
            [b, b, b, b, b, b, w, b],
            [b, b, b, b, w, w, b, b],
            [b, b, b, w, b, b, b, b],
            [b, w, w, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
        ],

        'A' => [
            [w, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
        ],
        'B' => [
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
        ],
        'C' => [
            [b, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, w],
        ],
        'D' => [
            [w, w, w, w, w, w, b, b],
            [w, b, b, b, b, b, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, w, b],
            [w, w, w, w, w, w, b, b],
        ],
        'E' => [
            [w, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
        ],
        'F' => [
            [w, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
        ],
        'G' => [
            [b, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, w, w, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, w, w, w, w, w, b],
        ],
        'H' => [
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
        ],
        'I' => [
            [w, w, w, w, w, w, w, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [w, w, w, w, w, w, w, b],
        ],
        'J' => [
            [b, b, b, w, w, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [w, b, b, b, b, w, b, b],
            [w, b, b, b, b, w, b, b],
            [b, w, w, w, w, b, b, b],
        ],
        'K' => [
            [w, b, b, b, w, w, b, b],
            [w, b, b, w, b, b, b, b],
            [w, b, w, b, b, b, b, b],
            [w, w, b, b, b, b, b, b],
            [w, b, w, b, b, b, b, b],
            [w, b, b, w, b, b, b, b],
            [w, b, b, b, w, b, b, b],
            [w, b, b, b, b, w, b, b],
        ],
        'L' => [
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
        ],
        'M' => [
            [w, b, b, b, b, b, b, w],
            [w, w, b, b, b, b, w, w],
            [w, b, w, b, b, w, b, w],
            [w, b, b, w, w, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
        ],
        'N' => [
            [w, b, b, b, b, b, b, w],
            [w, w, b, b, b, b, b, w],
            [w, b, w, b, b, b, b, w],
            [w, b, b, w, b, b, b, w],
            [w, b, b, b, w, b, b, w],
            [w, b, b, b, b, w, b, w],
            [w, b, b, b, b, b, w, w],
            [w, b, b, b, b, b, b, w],
        ],
        'O' => [
            [b, b, w, w, w, w, b, b],
            [b, w, b, b, b, b, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, w, b],
            [b, b, w, w, w, w, b, b],
        ],
        'P' => [
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
        ],
        'Q' => [
            [b, b, w, w, w, w, b, b],
            [b, w, b, b, b, b, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, b, w],
            [b, b, w, w, w, w, w, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, b, w, w],
        ],
        'R' => [
            [w, w, w, w, w, w, w, b],
            [w, b, b, b, b, b, b, w],
            [w, w, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
            [w, b, w, b, b, b, b, b],
            [w, b, b, w, w, b, b, b],
            [w, b, b, b, b, w, b, b],
            [w, b, b, b, b, b, w, b],
        ],
        'S' => [
            [b, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, b],
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
            [w, w, w, w, w, w, w, b],
        ],
        'T' => [
            [w, w, w, w, w, w, w, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
        ],
        'U' => [
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, w, b],
            [b, b, w, w, w, w, b, b],
        ],
        'V' => [
            [w, b, b, b, b, b, w, b],
            [w, b, b, b, b, b, w, b],
            [w, b, b, b, b, b, w, b],
            [b, w, b, b, b, w, b, b],
            [b, w, b, b, b, w, b, b],
            [b, b, w, b, w, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
        ],
        'W' => [
            [w, b, b, b, b, b, w, b],
            [w, b, b, b, b, b, w, b],
            [w, b, b, w, b, b, w, b],
            [b, w, b, w, b, w, b, b],
            [b, w, b, w, b, w, b, b],
            [b, w, b, w, b, w, b, b],
            [b, b, w, b, w, b, b, b],
            [b, b, w, b, w, b, b, b],
        ],
        'X' => [
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, w, b],
            [b, b, w, b, b, w, b, b],
            [b, b, b, w, w, b, b, b],
            [b, b, b, w, w, b, b, b],
            [b, b, w, b, b, w, b, b],
            [b, w, b, b, b, b, w, b],
            [w, b, b, b, b, b, b, w],
        ],
        'Y' => [
            [w, b, b, b, b, b, w, b],
            [b, w, b, b, b, w, b, b],
            [b, b, w, b, w, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
        ],
        'Z' => [
            [w, w, w, w, w, w, w, w],
            [b, b, b, b, b, b, w, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, w, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, w, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
        ],

        '0' => [
            [b, b, b, w, w, b, b, b],
            [b, b, w, b, b, w, b, b],
            [b, w, b, w, b, b, w, b],
            [b, w, b, w, b, b, w, b],
            [b, w, b, b, w, b, w, b],
            [b, w, b, b, w, b, w, b],
            [b, b, w, b, b, w, b, b],
            [b, b, b, w, w, b, b, b],
        ],
        '1' => [
            [b, w, w, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, w, w, w, w, w, b, b],
        ],
        '2' => [
            [b, b, w, w, w, w, b, b],
            [b, w, b, b, b, b, w, b],
            [w, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, w, w, w, b],
            [b, b, w, w, b, b, b, b],
            [b, w, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
        ],
        '3' => [
            [b, w, w, w, w, w, b, b],
            [w, b, b, b, b, b, w, b],
            [b, b, b, b, b, b, b, w],
            [b, b, w, w, w, w, w, b],
            [b, b, b, b, b, b, b, w],
            [b, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, w, b],
            [b, w, w, w, w, w, b, b],
        ],
        '4' => [
            [b, b, b, b, w, b, b, b],
            [b, b, b, w, w, b, b, b],
            [b, b, w, b, w, b, b, b],
            [b, w, b, b, w, b, b, b],
            [w, b, b, b, w, b, b, b],
            [w, w, w, w, w, w, w, w],
            [b, b, b, b, w, b, b, b],
            [b, b, b, b, w, b, b, b],
        ],
        '5' => [
            [w, w, w, w, w, w, w, w],
            [w, b, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, b, b],
            [b, b, b, b, b, b, w, b],
            [b, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, w, b],
            [b, w, w, w, w, w, b, b],
        ],
        '6' => [
            [b, b, w, w, w, w, w, w],
            [b, w, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, b, b],
            [w, b, b, b, b, b, w, b],
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, w, b],
            [b, b, w, w, w, w, b, b],
        ],
        '7' => [
            [w, w, w, w, w, w, w, w],
            [b, b, b, b, b, b, w, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, w, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, w, b, b, b, b, b, b],
            [w, b, b, b, b, b, b, b],
        ],
        '8' => [
            [b, b, w, w, w, w, b, b],
            [b, w, b, b, b, b, w, b],
            [b, w, b, b, b, b, w, b],
            [b, b, w, w, w, w, b, b],
            [b, w, b, b, b, b, w, b],
            [w, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, b, w],
            [b, w, w, w, w, w, w, b],
        ],
        '9' => [
            [b, b, w, w, w, w, b, b],
            [b, w, b, b, b, b, w, b],
            [w, b, b, b, b, b, b, w],
            [b, w, b, b, b, b, b, w],
            [b, b, w, w, w, w, w, w],
            [b, b, b, b, b, b, b, w],
            [w, b, b, b, b, b, w, b],
            [b, w, w, w, w, w, b, b],
        ],

        '-' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
        ],
        '_' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [w, w, w, w, w, w, w, w],
        ],
        '"' => [
            [b, b, w, b, w, b, b, b],
            [b, b, w, b, w, b, b, b],
            [b, b, w, b, w, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
        ],
        '{' => [
            [b, b, b, b, w, w, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [w, w, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, b, w, w, b, b],
        ],
        '}' => [
            [b, b, w, w, b, b, b, b],
            [b, b, b, b, w, b, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, w, w],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, w, b, b, b],
            [b, b, w, w, b, b, b, b],
        ],
        '[' => [
            [b, b, w, w, w, w, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, w, w, w, b, b],
        ],
        ']' => [
            [b, b, w, w, w, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, w, w, w, w, b, b],
        ],
        '(' => [
            [b, b, b, b, w, w, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, w, b, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, b, w, w, b, b],
        ],
        ')' => [
            [b, b, w, w, b, b, b, b],
            [b, b, b, b, w, b, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, b, w, b, b],
            [b, b, b, b, w, b, b, b],
            [b, b, w, w, b, b, b, b],
        ],
        ',' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, w, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, w, b, b, b, b, b],
        ],
        '=' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, w, w, w, w, w, w, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
        ],
        ':' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, w, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, w, b, b, b],
        ],
        '!' => [
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, w, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, w, b, b, b, b],
        ],
        '.' => [
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, b, b, b, b],
            [b, b, b, b, w, b, b, b],
        ],

        _ => [
            [w, w, w, w, w, w, w, w],
            [w, w, w, w, w, w, w, w],
            [w, w, w, w, w, w, w, w],
            [w, w, w, w, w, w, w, w],
            [w, w, w, w, w, w, w, w],
            [w, w, w, w, w, w, w, w],
            [w, w, w, w, w, w, w, w],
            [w, w, w, w, w, w, w, w],
        ]
    }
}
