use super::{Char, Font};

pub struct Monospace;

impl Char for [[bool; 8]; 16] {
    fn bits(&self) -> alloc::vec::Vec<alloc::vec::Vec<bool>> {
        alloc::vec![
            self[0].to_vec(),
            self[1].to_vec(),
            self[2].to_vec(),
            self[3].to_vec(),
            self[4].to_vec(),
            self[5].to_vec(),
            self[6].to_vec(),
            self[7].to_vec(),
            self[8].to_vec(),
            self[9].to_vec(),
            self[10].to_vec(),
            self[11].to_vec(),
            self[12].to_vec(),
            self[13].to_vec(),
            self[14].to_vec(),
            self[15].to_vec(),
        ]
    }
}

const O: bool = false;
const F: bool = true;

impl Font for Monospace {
    fn char(&self, c: char) -> alloc::vec::Vec<alloc::vec::Vec<bool>> {
        let c = match c {
            ' ' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '!' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '"' => [
                [O, O, O, O, O, O, O, O],
                [O, F, F, O, O, F, F, O],
                [O, F, F, O, O, F, F, O],
                [O, F, F, O, O, F, F, O],
                [O, F, F, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '#' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, O, F, F, O, O],
                [O, F, F, O, F, F, O, O],
                [F, F, F, F, F, F, F, O],
                [O, F, F, O, F, F, O, O],
                [O, F, F, O, F, F, O, O],
                [O, F, F, O, F, F, O, O],
                [O, F, F, O, F, F, O, O],
                [F, F, F, F, F, F, F, O],
                [O, F, F, O, F, F, O, O],
                [O, F, F, O, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '$' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, F, O, O, O, O],
                [F, F, O, F, O, O, O, O],
                [F, F, O, F, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, F, O, F, F, O],
                [O, O, O, F, O, F, F, O],
                [O, O, O, F, O, F, F, O],
                [O, O, O, F, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '%' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, F, F, O],
                [O, F, F, O, O, F, F, O],
                [O, F, F, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, F, F, O],
                [O, F, F, O, O, F, F, O],
                [O, F, F, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '&' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, F, F, F, O, O, O],
                [O, F, F, O, F, F, O, O],
                [O, F, F, O, F, F, O, O],
                [O, F, F, O, F, F, O, O],
                [O, O, F, F, F, O, O, O],
                [O, F, F, F, O, O, O, O],
                [F, F, O, F, F, O, F, O],
                [F, F, O, O, F, F, O, O],
                [F, F, O, O, F, F, O, O],
                [O, F, F, F, F, O, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '\'' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '(' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, F, F, F, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            ')' => [
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, F, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '*' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, O, O, F, F, O],
                [O, O, F, F, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [F, F, F, F, F, F, F, F],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, F, F, O, O],
                [O, F, F, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '+' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            ',' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '-' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '.' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '/' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '0' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, F, F, F, O],
                [F, F, O, F, F, F, F, O],
                [F, F, F, F, O, F, F, O],
                [F, F, F, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '1' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, F, O, O, O],
                [O, F, F, F, F, O, O, O],
                [O, F, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '2' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '3' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, F, F, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '4' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, F, F, O, O],
                [F, F, O, O, F, F, O, O],
                [F, F, O, O, F, F, O, O],
                [F, F, O, O, F, F, O, O],
                [F, F, F, F, F, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '5' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '6' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '7' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '8' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '9' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            ':' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            ';' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '<' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '=' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '>' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '?' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '@' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, O, F, O],
                [F, F, O, F, F, O, F, O],
                [F, F, O, F, F, O, F, O],
                [F, F, O, F, F, O, F, O],
                [F, F, O, F, F, O, F, O],
                [F, F, O, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'A' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'B' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'C' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'D' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'E' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, F, F, F, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'F' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, F, F, F, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'G' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'H' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'I' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'J' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [F, F, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'K' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, F, F, O, O],
                [F, F, F, F, F, O, O, O],
                [F, F, O, O, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'L' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'M' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, O, F, F, F, O],
                [F, F, F, F, F, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'N' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, O, O, F, F, O],
                [F, F, F, O, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, O, F, F, F, O],
                [F, F, O, O, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'O' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'P' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'Q' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'R' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'S' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'T' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, F, F],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'U' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'V' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, O, F, F, O, O],
                [O, O, F, F, F, O, O, O],
                [O, O, O, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'W' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, F, F, F, F, F, O],
                [F, F, F, O, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'X' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, O, F, F, O, O],
                [O, O, F, F, F, O, O, O],
                [O, F, F, O, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'Y' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'Z' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '[' => [
                [O, O, O, O, O, O, O, O],
                [O, O, F, F, F, F, F, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '\\' => [
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            ']' => [
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, F, F, O, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '^' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, O, O, O, O],
                [O, O, F, F, F, O, O, O],
                [O, F, F, O, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '_' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
            ],
            '`' => [
                [O, O, O, O, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'a' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'b' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'c' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'd' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'e' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'f' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, F, F, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'g' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'h' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'i' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, F, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'j' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, F, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'k' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, F, F, O, O],
                [F, F, O, F, F, O, O, O],
                [F, F, F, F, O, O, O, O],
                [F, F, F, F, O, O, O, O],
                [F, F, O, F, F, O, O, O],
                [F, F, O, O, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'l' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'm' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, O, F, F, O, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'n' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'o' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'p' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'q' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
            ],
            'r' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            's' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, F, F, F, O],
                [F, F, O, O, O, O, O, O],
                [F, F, O, O, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            't' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, F, F, F, F, F, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, O, O, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'u' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'v' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, O, F, F, O, O],
                [O, O, F, F, F, O, O, O],
                [O, O, O, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'w' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [F, F, O, F, O, F, F, O],
                [O, F, F, O, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'x' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, O, F, F, O, O],
                [O, O, F, F, F, O, O, O],
                [O, O, F, F, F, O, O, O],
                [O, F, F, O, F, F, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'y' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [F, F, O, O, O, F, F, O],
                [O, F, F, F, F, F, F, O],
                [O, O, O, O, O, F, F, O],
                [O, O, O, O, O, F, F, O],
                [F, F, F, F, F, F, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            'z' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [F, F, F, F, F, F, F, O],
                [O, O, O, O, F, F, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, F, F, O, O, O, O],
                [O, F, F, O, O, O, O, O],
                [F, F, F, F, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '{' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, F, F, F, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, F, F, F, O, O, O, O],
                [O, F, F, F, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, F, F, F, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '|' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '}' => [
                [O, O, O, O, O, O, O, O],
                [O, F, F, F, O, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, O, F, F, F, O],
                [O, O, O, O, F, F, F, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, O, O, F, F, O, O, O],
                [O, F, F, F, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            '~' => [
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, F, F, O, O, F, O],
                [O, F, F, F, F, F, F, O],
                [O, F, O, O, F, F, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
                [O, O, O, O, O, O, O, O],
            ],
            _ => return self.char(' '),
        };

        c.bits()
    }
}
